package com.xpleemoon.xmodulable.compiler;

public final class Constants {
    public static final String WARNING_TIPS = "DO NOT EDIT THIS FILE!!! IT WAS GENERATED BY XMODULABLE.";

    /**
     * 组建模块
     */
    public static final String KEY_XMODULE = "XModule";

    public static final String PACKAGE_OF_API = "com.xpleemoon.xmodulable.api";
    public static final String PACKAGE_OF_GENERATE = "com.xpleemoon.xmodulable.api.loaders";
    public static final String PACKAGE_OF_ANNOTATION = "com.xpleemoon.xmodulable.annotation";

    public static final String SDK_NAME = "XModulable";
    public static final String PREFIX_OF_LOGGER = SDK_NAME + "::Compiler >>> ";
    /**
     * 类名分隔符
     */
    public static final String SEPARATOR_OF_CLASS_NAME = "$$";
    public static final String CLASS_OF_LOADER = "Loader";
    public static final String CLASS_OF_INJECTOR = SDK_NAME + "Injector";
    public static final String METHOD_OF_LOAD_INTO = "loadInto";
    public static final String METHOD_OF_INJECT = "inject";
    public static final String PARAMETER_OF_XMODULABLE_OPTIONS = "options";
    public static final String PARAMETER_OF_TARGET = "target";

    public static final String XMODULABLE = PACKAGE_OF_API + ".XModulable";
    public static final String XMODULABLE_OPTIONS = PACKAGE_OF_API + ".XModulableOptions";
    public static final String XMODULE_LOADER = PACKAGE_OF_API + ".template.XModuleLoader";
    public static final String UNKNOWN_MODULE_EXCEPTION = PACKAGE_OF_API + ".exception.UnknownModuleException";

    public static final String ANNOTATION_TYPE_XMODULE = PACKAGE_OF_ANNOTATION + ".XModule";
    public static final String ANNOTATION_TYPE_INJECT_XMODULE = PACKAGE_OF_ANNOTATION + ".InjectXModule";
}
