package com.xpleemoon.component.compiler;

public class Constants {
    public static final String WARNING_TIPS = "DO NOT EDIT THIS FILE!!! IT WAS GENERATED BY COMPONENT.";

    public static final String KEY_COMPONENT_NAME = "componentName";

    public static final String PACKAGE_OF_API = "com.xpleemoon.component.api";
    public static final String PACKAGE_OF_GENERATE = "com.xpleemoon.component.api.generate";
    public static final String PACKAGE_OF_ANNOTATION = "com.xpleemoon.component.annotations";

    public static final String SDK_NAME = "Component";
    public static final String PREFIX_OF_LOGGER = SDK_NAME + "::Compiler >>> ";
    public static final String SEPARATOR_OF_CLASS_NAME = "$$";
    public static final String CLASS_NAME_LOADER = "Loader";
    public static final String METHOD_LOAD_INTO = "loadInto";
    public static final String PARAMETER_OF_COMPONENT_OPTIONS = "componentOptions";

    public static final String COMPONENT_MANAGER = PACKAGE_OF_API + ".ComponentManager";
    public static final String COMPONENT_OPTIONS = PACKAGE_OF_API + ".ComponentOptions";
    public static final String COMPONENT_OPTIONS_BUILDER = COMPONENT_OPTIONS + ".Builder";
    public static final String ICOMPONENT_LOADER = PACKAGE_OF_API + ".template.IComponentLoader";

    public static final String ANNOTATION_TYPE_COMPONENT = PACKAGE_OF_ANNOTATION + ".Component";
}
